### ISSUE TITLE
Conflict with this plugin

### ISSUE THREAD

**Issue by mkstephens** [wgcowan/VideoStream#7]
I discovered that this plugin was creating a conflict with the OAI-PMH Repository plugin by creating an empty first line in the script. This was returning an error on our OAI-PMH Repository URL. When I deactivated this plugin, the error went away.

Let me know if there is a new version that fixes this problem. I have 2.1 installed on my Omeka instance.

**Comment by wgcowan** [comment]
There is a recent update, Release 2.3, with significant improvements by Daniel Berthereau. I briefly tested this with the OAI-PMH Repository plugin but I am not all that familar with that plugin so I might not have hit upon your specific problem. Please upgrade and let me know if it works.

Thanks
